name: Build Indexer Manger Docker
on:
  workflow_dispatch:
    inputs:
      isLatest:
        description: 'Add latest tag'
        default: 'true'
        required: true

jobs:
  manager-build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: massbit
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get updated manager version
        id: get-manager-version
        run: |
          sh .github/workflows/scripts/managerVersion.sh

      - name: Build and push
        if: github.event.inputs.isLatest == 'false'
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: arm64,amd64
          file: ./packages/manager/Dockerfile
          tags: massbit/maanger:v${{ steps.get-manager-version.outputs.MANAGER_VERSION }}
          build-args: RELEASE_VERSION=${{ steps.get-manager-version.outputs.MANAGER_VERSION }}

      - name: Build and push
        if: github.event.inputs.isLatest == 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: arm64,amd64
          file: ./packages/manager/Dockerfile
          tags: massbit/manager:v${{ steps.get-manager-version.outputs.MANAGER_VERSION }},massbit/manager:latest
          build-args: RELEASE_VERSION=${{ steps.get-manager-version.outputs.MANAGER_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

