name: Prerelease
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Block concurrent executions
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump-prerelease-publish:
    name: Bump prerelease & publish
    needs: pre-ci
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && !startsWith(github.event.head_commit.message, '[release]') && github.repository == 'massbitprotocol/substrate-indexer'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - uses: marceloprado/has-changed-path@v1
        id: changed-types
        with:
          paths: packages/types

      - uses: marceloprado/has-changed-path@v1
        id: changed-common
        with:
          paths: packages/common

      - uses: marceloprado/has-changed-path@v1
        id: changed-cli
        with:
          paths: packages/cli

      - uses: marceloprado/has-changed-path@v1
        id: changed-manager
        with:
          paths: packages/manager

      - uses: marceloprado/has-changed-path@v1
        id: changed-query
        with:
          paths: packages/query

      - run: yarn

      - name: build
        run: yarn workspaces foreach run build

      - name: Bump types & deploy
#        if: steps.changed-types.outputs.changed == 'true'
        working-directory: packages/types
        run: echo "Changes exist in types" && yarn version prerelease && yarn npm publish --access public --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump common & deploy
#        if: steps.changed-common.outputs.changed == 'true'
        working-directory: packages/common
        run: echo "Changes exist in common" && yarn version prerelease && yarn npm publish --access public --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump cli & deploy
#        if: steps.changed-cli.outputs.changed == 'true'
        working-directory: packages/cli
        run: echo "Changes exist in cli" && yarn version prerelease && yarn npm publish --access public --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump manger & deploy
#        if: steps.changed-manager.outputs.changed == 'true'
        working-directory: packages/manager
        run: echo "Changes exist in manager" && yarn version prerelease && yarn npm publish --access public --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump query & deploy
#        if: steps.changed-query.outputs.changed == 'true'
        working-directory: packages/query
        run: echo "Changes exist in query" && yarn version prerelease && yarn npm publish --access public --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: '[SKIP CI] Prerelease'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
