name: "Release"
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  pre-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Build-Publish:
    name: Build-Publish
    needs: pre-ci
    if: "!startsWith(github.event.head_commit.message, '[SKIP CI]') && startsWith(github.event.head_commit.message, '[release]') && github.repository == 'massbitprotocol/substrate-indexer'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - uses: marceloprado/has-changed-path@v1
        id: changed-types
        with:
          paths: packages/types

      - uses: marceloprado/has-changed-path@v1
        id: changed-common
        with:
          paths: packages/common

      - uses: marceloprado/has-changed-path@v1
        id: changed-cli
        with:
          paths: packages/cli

      - uses: marceloprado/has-changed-path@v1
        id: changed-manager
        with:
          paths: packages/manager

      - uses: marceloprado/has-changed-path@v1
        id: changed-query
        with:
          paths: packages/query

      - run: yarn

      - name: build
        run: yarn workspaces foreach run build

      - name: Publish Types
        if: steps.changed-types.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/types
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish Common
        if: steps.changed-common.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/common
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish CLI
        if: steps.changed-cli.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/cli
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish Manager
        if: steps.changed-manager.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/manager
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Publish Query
        if: steps.changed-query.outputs.changed == 'true'
        uses: ./.github/actions/create-release
        with:
          package-path: packages/query
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
